const images = {
    aditya:require('./aditya.jpg').default,
    arjun:require('./arjun.jpg').default,
    charan:require('./charan.jpg').default,
    chirasmayi:require('./chirasmayi.jpg').default,
    karthik:require('./karthik.jpg').default,
    mounika:require('./mounika.jpg').default,
    naveen:require('./naveen.jpg').default,
    ncr:require('./ncr.jpg').default,
    niharika:require('./niharika.jpg').default,
    nitin:require('./nitin.jpg').default,
    nitya:require('./nitya.jpg').default,
    ruchitha:require('./ruchitha.jpg').default,
    shifa:require('./shifa.jpg').default,
    shreshta:require('./shreshta.jpg').default,
    varshitha:require('./varshitha.jpg').default,
    tarun:require('./tarun.jpg').default,
    jagadeesh:require('./jagadeesh.jpg').default,
    koushik:require('./koushik.jpg').default,
    sanju:require('./sanju.jpeg').default,
    anudeep:require('./anudeep.jpeg').default,
    sagar:require('./sagar.jpeg').default,
    koushika:require('./kaushika.jpeg').default,
}
export default images;